# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: python:3
    steps:
      - name: Instalar paquetes
        run: pip install -r requirements.txt

      - name: Ejecutar pruebas
        run: python3 manage.py run tests

  build:
    runs-on: docker
    steps:
      - name: Construir imagen desde dockerfile
        run: docker build . -t 192.168.5.3:5000/proyecto/app:$GITHUB_SHA

      - name: Pushear imagen a registry
        run: docker push 192.168.5.3:5000/proyecto/app:$GITHUB_SHA


  deploy:
    runs-on: centos:7
    steps:
      - name: Instalar epel 
        run: yum install -y epel

      - name: Instalar kubectl
        run: yum install -y kubectl

      - name: Deploy a test env 
        run: kubectl -n test set-image deployments/app  192.168.5.3:5000/proyecto/app:$GITHUB_SHA

      - name: Deploy a Staging env
        trigger: manual
        run: kubectl -n staging set-image deployments/app  192.168.5.3:5000/proyecto/app:$GITHUB_SHA

      - name: Deploy a Productiojn env
        trigger: manual
        run: kubectl -n prod set-image deployments/app  192.168.5.3:5000/proyecto/app:$GITHUB_SHA


